/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdjudicatorSlides: typeof import('./components/slides/AdjudicatorSlides.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    BestSlides: typeof import('./components/slides/BestSlides.vue')['default']
    Button: typeof import('./components/common/Button.vue')['default']
    Card: typeof import('./components/common/Card.vue')['default']
    DraggableList: typeof import('./components/common/DraggableList.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    Field: typeof import('./components/common/Field.vue')['default']
    FlexibleInput: typeof import('./components/common/FlexibleInput.vue')['default']
    InputLabel: typeof import('./components/common/InputLabel.vue')['default']
    LazyItem: typeof import('./components/common/LazyItem.vue')['default']
    LinkList: typeof import('./components/common/LinkList.vue')['default']
    LinkListItem: typeof import('./components/common/LinkListItem.vue')['default']
    List: typeof import('./components/common/List.vue')['default']
    ListItem: typeof import('./components/common/ListItem.vue')['default']
    LoadingContainer: typeof import('./components/common/LoadingContainer.vue')['default']
    LoadingState: typeof import('./components/common/LoadingState.vue')['default']
    NumberBox: typeof import('./components/common/NumberBox.vue')['default']
    PoiSlides: typeof import('./components/slides/PoiSlides.vue')['default']
    ReloadButton: typeof import('./components/common/ReloadButton.vue')['default']
    ResultsEditor: typeof import('./components/results/ResultsEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreChange: typeof import('./components/mstat/ScoreChange.vue')['default']
    ScoreHistogram: typeof import('./components/mstat/ScoreHistogram.vue')['default']
    ScoreRange: typeof import('./components/mstat/ScoreRange.vue')['default']
    Section: typeof import('./components/common/Section.vue')['default']
    SideHeatmap: typeof import('./components/mstat/SideHeatmap.vue')['default']
    SideMarginHeatmap: typeof import('./components/mstat/SideMarginHeatmap.vue')['default']
    SidePieChart: typeof import('./components/mstat/SidePieChart.vue')['default']
    SideScatter: typeof import('./components/mstat/SideScatter.vue')['default']
    Slides: typeof import('./components/slides/Slides.vue')['default']
    SlideShow: typeof import('./components/slides/SlideShow.vue')['default']
    SlidesWrapper: typeof import('./components/slides/SlidesWrapper.vue')['default']
    SpeakerSlides: typeof import('./components/slides/SpeakerSlides.vue')['default']
    Table: typeof import('./components/common/Table.vue')['default']
    TeamPerformance: typeof import('./components/mstat/TeamPerformance.vue')['default']
    TeamSlides: typeof import('./components/slides/TeamSlides.vue')['default']
    TournamentNotice: typeof import('./components/common/TournamentNotice.vue')['default']
  }
}
