import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function load(path: string) {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('AdminRoundOperationsHub', () => {
  it('contains horizontal round bar, task switcher, and force compile lane', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('round-bar')
    expect(source).toContain('task-flow')
    expect(source).toContain('activeTask')
    expect(source).toContain('selectTask(task.key)')
    expect(source).toContain('task-state-chip')
    expect(source).not.toContain('前段: {task}')
    expect(source).toContain('運営ステップ')
    expect(source).toContain('ラウンド結果確認')
    expect(source).not.toContain('提出確認・ラウンド結果集計')
    expect(source).toContain('対戦表作成')
    expect(source).toContain('ラウンド公開設定')
    expect(source).not.toContain(
      '対戦表作成でチーム/ジャッジごとの参照ラウンドを選び、「確定」で参照集計を自動確定します。'
    )
    expect(source).not.toContain('対戦生成と保存は対戦表設定で実行します。')
    expect(source).toContain('runAutoCompilePreview')
    expect(source).toContain("missing_data_policy: 'exclude'")
    expect(source).toContain('autoCompilePreviewPayload')
    expect(source).toContain('compileAutoError')
    expect(source).not.toContain('再読み込み時に、提出データから集計レポートを自動再計算します（未提出は除外）。')
    expect(source).not.toContain('集計レポートを再計算しました（未提出は除外）。')
    expect(source).not.toContain('未提出のジャッジ評価があります（提出 {submitted}/{expected}）。')
    expect(source).toContain('未完了（提出 {submitted}/{expected}）')
    expect(source).not.toContain("<strong>{{ $t('集計レポート') }}</strong>")
    expect(source).toContain('compileForcePreviewButtonLabel')
    expect(source).toContain('includeLabelsFromRoundDetails')
    expect(source).toContain('DRAW_REFERENCE_COMPILED_ID_KEY')
    expect(source).toContain('reference_compiled_id')
    expect(source).toContain('selectedRoundReferenceCompiledId')
    expect(source).toContain('selectedCompileDiffBaselineCompiledId')
    expect(source).toContain('@update:reference-compiled-id')
    expect(source).toContain('@update:reference-compiled-rounds')
    expect(source).toContain('roundReferenceDrafts')
    expect(source).toContain('onDrawReferenceCompiledIdUpdate')
    expect(source).toContain('onDrawReferenceCompiledRoundsUpdate')
    expect(source).toContain('readDrawReferenceCompiledId')
    expect(source).toContain('resolveLatestCompiledIdContainingRound')
    expect(source).not.toContain('compileDiffBaselineMode')
    expect(source).toContain('compileRows')
    expect(source).toContain('compileAdjudicatorRows')
    expect(source).toContain('compileScope')
    expect(source).toContain('teamPreviewBlocked')
    expect(source).toContain('adjudicatorPreviewBlocked')
    expect(source).toContain('showForcePreviewButton')
    expect(source).toContain('runTeamPreview')
    expect(source).toContain('runAdjudicatorPreview')
    expect(source).toContain('openScopedForcePreviewModal')
    expect(source).toContain('openCompileOptionsModal')
    expect(source).toContain('compileOptionsModalOpen')
    expect(source).toContain('RankingPriorityEditor')
    expect(source).toContain('adjudicatorRankingPriorityOptions')
    expect(source).toContain('adjudicator_ranking_priority')
    expect(source).not.toContain('{scope}')
    expect(source).not.toContain(
      '現在 server/core ではジャッジ専用の集計オプションは提供されていません。共通オプションで集計します。'
    )
    expect(source).toContain('buildCompileOptions')
    expect(source).toContain('selectedRoundAdjudicatorCompileStatusLabel')
    expect(source).not.toContain(':show-source-rounds="false"')
    expect(source).not.toContain('v-model:source-rounds')
    expect(source).not.toContain(':source-round-options')
    expect(source).toContain('selectedRoundReferenceCompiledRounds')
    expect(source).toContain('normalizeCompiledRoundNumbers')
    expect(source).toContain('DRAW_REFERENCE_COMPILED_ROUNDS_KEY')
    expect(source).toContain('readDrawReferenceCompiledRounds')
    expect(source).toContain('effectiveCompileTargetRounds')
    expect(source).toContain('selectedRoundReferenceCompiledLabel')
    expect(source).toContain('effectiveCompileTargetRoundsLabel')
    expect(source).toContain('compileScopeLabel.value')
    expect(source).not.toContain('このステップでは再読み込み時に集計レポートを再計算します（未提出除外）。')
    expect(source).toContain('このラウンドより前を一括非公開')
    expect(source).toContain('canShowPriorRoundsHideSwitch')
    expect(source).toContain('onPriorRoundsHideToggle')
    expect(source).toContain('priorRoundsFullyHidden')
    expect(source).toContain('applyCompileDraftFromRound')
    expect(source).toContain('selectedRoundData.value?.userDefinedData')
    expect(source).not.toContain('compile-round-picker')
  })

  it('updates compile diff indicators from draw reference compiled snapshot', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('applyClientBaselineDiff')
    expect(source).toContain('stripDiffFields')
    expect(source).toContain('selectedCompileDiffBaselineCompiledId')
    expect(source).toContain('selectedCompileDiffBaselineCompiled')
    expect(source).toContain('selectedCompileDiffBaselineRows')
    expect(source).toContain('selectedRoundReferenceCompiledId')
    expect(source).toContain('selectedRoundLatestSavedCompiledId')
    expect(source).toContain('selectedRoundLatestSavedCompiled')
    expect(source).toContain('isShowingSavedCompiledForSelectedRound')
    expect(source).toContain('showCompileDiffLegend')
    expect(source).toContain('v-if="snapshotIncludesSelectedRound && hasVisibleCompileRows"')
    expect(source).toContain('selectedRoundSavedCompiledBanner')
    expect(source).toContain('集計結果を再計算できませんでした。提出データを確認して再読み込みしてください。')
  })

  it('supports team and adjudicator ranking lists in compile report', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('CategoryRankingTable')
    expect(source).toContain('compileAdjudicatorColumns')
    expect(source).toContain('compileAdjudicatorColumnLabel')
    expect(source).toContain('downloadCompileAdjudicatorReportCsv')
    expect(source).not.toContain('FairnessAnalysisCharts')
    expect(source).not.toContain('SidePieChart')
    expect(source).not.toContain('ScoreHistogram')
    expect(source).not.toContain('compile-report-tabs')
    expect(source).not.toContain('カテゴリ別順位一覧')
    expect(source).not.toContain('公平性')
  })

  it('stores selected task per round and defaults to first incomplete step', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('roundTaskSelection')
    expect(source).toContain('recommendedTaskForRound')
    expect(source).toContain('resolveTaskForRound')
    expect(source).toContain('[roundNumber]: task')
    expect(source).toContain('task: nextTask')
  })

  it('isolates preview payload by current round input and clears unsaved preview on round/task switch', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('shouldUseCompilePreviewPayload')
    expect(source).toContain('compileWorkflow.hasPreview')
    expect(source).toContain('!compileWorkflow.previewStale')
    expect(source).toContain("previousTask === 'submissions' && nextTask !== 'submissions'")
    expect(source).toContain('if (nextRound !== previousRound)')
    expect(source).toContain('clearUnsavedCompilePreview()')
    expect(source).toContain('compileWorkflow.clearPreview()')
    expect(source).toContain('compiledStore.clearPreview()')
    expect(source).toContain("compileMessage.value = ''")
  })

  it('adds strict submission guards before compile and draw generation', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('scopeNeedsBallotGapCheck')
    expect(source).toContain('scopeNeedsFeedbackGapCheck')
    expect(source).toContain('teamPreviewBlocked')
    expect(source).toContain('adjudicatorPreviewBlocked')
    expect(source).toContain('selectedRoundHasDraw')
    expect(source).not.toContain('selectedRoundBallotGapWarning')
    expect(source).toContain('snapshotIncludesSelectedRound')
    expect(source).toContain('resolveCompiledRoundSet')
    expect(source).toContain('hasRoundNewSubmissionsAfterLatestSavedCompiled')
    expect(source).toContain('hasNewSubmissionsAfterSelectedRoundSavedCompiled')
    expect(source).toContain('選択ラウンドのチーム評価が揃っていないため、集計を実行できません。')
    expect(source).not.toContain('未提出のチーム評価があります（提出 {submitted}/{expected}）。')
  })

  it('keeps submission coverage data in a hub-local snapshot', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('const hubSubmissions = ref<Submission[]>([])')
    expect(source).toContain('refreshHubSubmissions')
    expect(source).toContain("api.get('/submissions', { params: { tournamentId: currentTournamentId } })")
    expect(source).not.toContain('submissionsStore.submissions.forEach')
  })

  it('invalidates stale refresh, submission, preview, and compiled-history requests', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('createLatestRequestGate')
    expect(source).toContain('const refreshGate = createLatestRequestGate()')
    expect(source).toContain('const hubSubmissionsGate = createLatestRequestGate()')
    expect(source).toContain('const autoCompilePreviewGate = createLatestRequestGate()')
    expect(source).toContain('const compiledHistoryGate = createLatestRequestGate()')
    expect(source).toContain('hubSubmissionsGate.invalidate()')
    expect(source).toContain('compiledHistoryGate.invalidate()')
    expect(source).toContain('autoCompilePreviewGate.invalidate()')
    expect(source).toContain('if (!refreshGate.isCurrent(token)) return')
    expect(source).toContain('if (!hubSubmissionsGate.isCurrent(token)) return')
    expect(source).toContain('if (!autoCompilePreviewGate.isCurrent(token)) return')
    expect(source).toContain('if (!compiledHistoryGate.isCurrent(token)) return')
  })

  it('reads compiled rounds using r-or-round fallback for status chips', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).toContain('item?.r ?? item?.round')
  })

  it('embeds destination panels inline instead of using page navigation buttons', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    expect(source).not.toContain('<iframe')
    expect(source).toContain('AdminRoundAllocation')
    expect(source).toContain('AdminTournamentSubmissions')
    expect(source).toContain('DrawPreviewTable')
    expect(source).not.toContain('buildEmbedUrl(')
    expect(source).not.toContain('openAllocationPage')
    expect(source).not.toContain('openRawResultPage')
    expect(source).not.toContain('openSubmissionsPage')
    expect(source).not.toContain('openReportsPage')
  })

  it('shows submission overview and venue-based submission table with search', () => {
    const source = load('src/views/admin/AdminRoundOperationsHub.vue')
    const submissionsView = load('src/views/admin/AdminTournamentSubmissions.vue')
    expect(source).not.toContain('提出スピード詳細')
    expect(source).not.toContain('selectedRoundSubmissionSpeed')
    expect(source).not.toContain('selectedRoundSubmissionDelayRows')
    expect(source).not.toContain("submissionEvaluationTab === 'team'")
    expect(source).not.toContain("submissionEvaluationTab === 'judge'")
    expect(source).not.toContain(':split-active-key="submissionEvaluationTab"')
    expect(source).not.toContain("提出者情報不足: Ballot {ballot} / Feedback {feedback}")
    expect(source).toContain('会場別提出状況')
    expect(source).toContain('submissionPreviewSearchQuery')
    expect(source).toContain('filteredSubmissionPreviewRows')
    expect(source).toContain('会場・チーム・提出者で検索')
    expect(source).toContain('submissionPreviewRows')
    expect(source).toContain(':show-submission-columns="true"')
    expect(source).toContain(':focus-edit-only="true"')
    expect(source).toContain(':close-on-save="true"')
    expect(source).toContain('@saved="handleSubmissionEditorSaved"')
    expect(source).toContain('@deleted="handleSubmissionEditorDeleted"')
    expect(source).toContain('openSubmissionEditorModal')
    expect(source).not.toContain('watch(submissionEditorTarget')
    expect(submissionsView).toContain('splitActiveKey')
    expect(submissionsView).toContain('focusEditOnly')
    expect(submissionsView).toContain('closeOnSave')
    expect(submissionsView).toContain("emit('saved', updatedSubmission)")
    expect(submissionsView).toContain("emit('deleted', deleted as Submission)")
  })

  it('uses round tie settings to control ballot winner options without an unselected option', () => {
    const submissionsView = load('src/views/admin/AdminTournamentSubmissions.vue')
    expect(submissionsView).toContain("const DRAW_WINNER_OPTION_VALUE = '__draw__'")
    expect(submissionsView).toContain('const editingBallotAllowDraw = computed(() =>')
    expect(submissionsView).toContain('allowLowTieWin: found?.userDefinedData?.allow_low_tie_win !== false')
    expect(submissionsView).toContain('allowWinnerScoreMismatch: roundAllowsWinnerScoreMismatch(found?.userDefinedData)')
    expect(submissionsView).toContain('const editingBallotWinnerOptions = computed<Array<{ value: string; label: string }>>(() => {')
    expect(submissionsView).toContain('v-for="option in editingBallotWinnerOptions"')
    expect(submissionsView).not.toMatch(
      /:label=\"\$t\('勝者'\)\"[\s\S]{0,220}<option value=\"\">\{\{ \$t\('未選択'\) \}\}<\/option>/
    )
  })

  it('increments score-editing spinners by whole points', () => {
    const submissionsView = load('src/views/admin/AdminTournamentSubmissions.vue')
    expect(submissionsView).toContain('step="1"')
    expect(submissionsView).not.toContain('step="0.1"')
  })
})
