import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function load(path: string) {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('AdminTournamentCompiled V2', () => {
  it('organizes the report workflow into three section tabs with rankings as the default', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('reportUxV3Enabled')
    expect(source).toContain('activeReportSection')
    expect(source).toContain('reportSectionOptions')
    expect(source).toContain('レポート表示')
    expect(source).not.toContain('タブは実行ではなく表示切替です。')
    expect(source).not.toContain('現在: {label} - {description}')
    expect(source).toContain('カテゴリ別順位一覧')
    expect(source).toContain('公平性')
    expect(source).toContain('発表出力')
    const operationsTabIndex = source.indexOf("key: 'operations'")
    const announcementTabIndex = source.indexOf("key: 'announcement'")
    const fairnessTabIndex = source.indexOf("key: 'fairness'")
    expect(operationsTabIndex).toBeGreaterThan(-1)
    expect(announcementTabIndex).toBeGreaterThan(-1)
    expect(fairnessTabIndex).toBeGreaterThan(-1)
    expect(operationsTabIndex).toBeLessThan(announcementTabIndex)
    expect(announcementTabIndex).toBeLessThan(fairnessTabIndex)
    expect(source).not.toContain("{ key: 'analysis'")
    expect(source).toContain("'operations'")
  })

  it('separates report views into prelim and break phases when break rounds exist', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    const messages = load('src/i18n/messages.ts')
    expect(source).toContain('reportDisplayOptions')
    expect(source).toContain('effectiveReportPhase')
    expect(source).toContain('setActiveReportPhase')
    expect(source).toContain('setReportDisplay')
    expect(source).toContain('予選順位一覧')
    expect(source).toContain('ブレイク順位一覧')
    expect(source).toContain('予選発表出力')
    expect(source).toContain('ブレイク発表出力')
    expect(source).toContain('予選統計')
    expect(source).toContain('ブレイク結果統計')
    expect(source).toContain('breakRoundNumbersInCompiled')
    expect(source).toContain('break_outcome')
    expect(source).toContain('準優勝')
    expect(messages).toContain('予選結果')
    expect(messages).toContain('ブレイク結果')
  })

  it('guards new report sections behind a dedicated feature flag', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    const flags = load('src/config/feature-flags.ts')
    expect(source).toContain('isAdminReportsUxV3Enabled')
    expect(flags).toContain('VITE_ADMIN_REPORTS_UX_V3')
  })

  it('splits top-level setup into required compile flow and optional existing-report selection', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('新規仮集計')
    expect(source).toContain('既存レポート')
    expect(source).toContain("$t('提出状況')")
    expect(source).toContain('report-setup-grid')
    expect(source).toContain("$t('ラウンド選択')")
    expect(source).toContain("$t('集計実行')")
    expect(source).toContain("$t('集計結果を保存')")
    expect(source).not.toContain('Step 1:')
    expect(source).not.toContain('Step 2:')
    expect(source).not.toContain('Step 3:')
    expect(source).toContain('v-model="compileRounds"')
    expect(source).toContain('type="checkbox"')
    expect(source).toContain('showForceCompileAfterError')
    expect(source).toContain('existing-report-list')
    expect(source).toContain("$t('日時')")
    expect(source).toContain("$t('考慮ラウンド')")
    expect(source).toContain("$t('メモ')")
    expect(source).toContain("$t('操作')")
    expect(source).toContain("$t('表示')")
    expect(source).toContain("$t('削除')")
    expect(source).not.toContain('CompiledSnapshotSelect')
    expect(source).not.toContain('表示するレポート')
    expect(source).toContain('roundSubmissionSummaries.length > 0')
    expect(source).toContain('submissionOperationsLinkForRound')
    expect(source).toContain('提出状況を確認')
    expect(source).not.toContain('提出状況サマリー')
    expect(source).not.toContain('レポート概要')
  })

  it('routes submission remediation to round operations submissions tab', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('submissionOperationsLinkForRound')
    expect(source).toContain('提出状況を確認')
    expect(source).not.toContain('`/admin/${tournamentId}/submissions`')
    expect(source).toContain('/operations')
    expect(source).toContain('?task=submissions')
  })

  it('invalidates stale page and compiled-history refreshes across tournament switches', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('createLatestRequestGate')
    expect(source).toContain('const refreshGate = createLatestRequestGate()')
    expect(source).toContain('const compiledHistoryGate = createLatestRequestGate()')
    expect(source).toContain('compiledHistoryGate.invalidate()')
    expect(source).toContain('if (!refreshGate.isCurrent(token)) return')
    expect(source).toContain('if (!compiledHistoryGate.isCurrent(token)) return')
    expect(source).toContain('hasLoaded.value = false')
  })

  it('keeps rankings focused and removes operation-risk frame content', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('operations-results')
    expect(source).toContain('カテゴリ別順位一覧')
    expect(source).toContain('rankingLabels')
    expect(source).toContain('CSVダウンロード（コメントシートのみ）')
    expect(source).toContain("v-if=\"activeLabel === 'adjudicators'\"")
    expect(source).toContain('参加者CSVダウンロード')
    expect(source).not.toContain('コメントシートCSV')
    expect(source).not.toContain("{{ $t('参加者CSV') }}")
    expect(source).not.toContain('順位一覧の対象を切り替えます。')
    expect(source).not.toContain('最終確定前に、順位・差分・境界をこの一覧で先に確認してください。')
    expect(source).not.toContain('確定リスク')
    expect(source).not.toContain('operationRisks')
    expect(source).not.toContain('operationRiskSeverityLabel')
  })

  it('keeps entity tabs visible and disables them when no data exists', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('rankingLabels')
    expect(source).toContain('slideAvailableLabels')
    expect(source).toContain(':disabled="!isEntityLabelEnabled(label)"')
    expect(source).toContain('entityLabelHasData')
    expect(source).toContain('enabledEntityLabels')
    expect(source).not.toContain("v-if=\"slideAvailableLabels.includes(label)\"")
  })

  it('uses common diff baseline selector and defaults to previous snapshot', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    const helper = load('src/utils/compiled-snapshot.ts')
    const selector = load('src/components/common/CompiledDiffBaselineSelect.vue')
    expect(source).toContain('CompiledDiffBaselineSelect')
    expect(source).toContain('compileDiffBaselineSelection')
    expect(source).toContain('diffBaselineCompiledOptions')
    expect(source).toContain('applyDefaultDiffBaselineSelection')
    expect(source).toContain('resolvePreviousCompiledId')
    expect(source).not.toContain('差分基準: {baseline}')
    expect(source).not.toContain('latest-label')
    expect(selector).toContain("props.placeholder || t('未選択')")
    expect(selector).toContain(':placeholder="placeholderText"')
    expect(helper).toContain('formatCompiledSnapshotOptionLabel')
    expect(helper).toContain('resolvePreviousCompiledId')
  })

  it('applies selected diff baseline immediately on the client without waiting for recompilation', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('applyClientBaselineDiff')
    expect(source).toContain('stripDiffFields')
    expect(source).toContain('selectedDiffBaselineCompiled')
    expect(source).toContain('selectedDiffBaselineRows')
    expect(source).toContain('resultSourceForLabel')
    expect(source).toContain('selectedDiffBaselineCompiledId.value.length > 0')
  })

  it('adds fairness summary cards for side, matchup, and judge allocation bias', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('fairnessSideSummary')
    expect(source).toContain('fairnessMatchupSummary')
    expect(source).toContain('fairnessJudgeSummary')
    expect(source).toContain('fairnessAlertCount')
    expect(source).toContain('ジャッジ担当回数')
    expect(source).toContain('Number.isInteger(round.round) && round.round >= 1')
  })

  it('adds judge strictness outlier insights on the fairness section', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('buildJudgeStrictnessRows')
    expect(source).toContain('judgeFeedbackRankingRows')
    expect(source).toContain('judgeFeedbackRankingOutliers')
    expect(source).toContain('ジャッジ評価')
    expect(source).toContain('judgeBallotStrictnessRows')
    expect(source).toContain('canShowJudgeBallotStrictness')
    expect(source).toContain('チーム評価の厳しさ')
    expect(source).toContain('row.matchCount')
    expect(source).toContain('strictnessBarStyle')
    expect(source).not.toContain('strictnessPointStyle')
    expect(source).toContain('strictness-bar-track')
    expect(source).not.toContain('strictness-plot')
  })

  it('removes announcement summary and boundary sections while keeping announcement export tools', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('発表準備サマリー')
    expect(source).not.toContain('発表境界')
    expect(source).not.toContain('breakBoundarySummary')
    expect(source).toContain('表彰コピー')
    expect(source).toContain('受賞者CSV')
  })

  it('integrates analysis charts into fairness section with lazy readiness and empty state', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('分析（公平性タブ統合）')
    expect(source).not.toContain('分析は公平性タブで確認できます。')
    expect(source).toContain('analysisChartsReady')
    expect(source).toContain('canShowAnalysisCharts')
    expect(source).toContain('analysisEmptyState')
    expect(source).toContain('fairnessAnalysisResults')
    expect(source).toContain('speakerPerformanceResults')
    expect(source).toContain('adjudicatorPerformanceResults')
    expect(source).toContain('スピーカー成績')
    expect(source).toContain('ジャッジ成績')
    expect(source).not.toContain('スピーカー成績のプロット')
    expect(source).not.toContain('ジャッジ成績のプロット')
    expect(source).toContain('<TeamPerformance')
    expect(source).toContain('fairnessScoreKey')
    expect(source).toContain(':show-team-performance="true"')
    expect(source).not.toContain(":show-team-performance=\"activeLabel === 'teams'\"")
    expect(source).not.toContain('showAnalysisSection')
    expect(source).toContain(':use-cards="true"')
    expect(source).toContain('<EmptyState')
    expect(source).toContain('fairness-analysis-chart-card')
  })

  it('keeps score range display fixed to max-score order without sort controls', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('スコア範囲ソート')
    expect(source).not.toContain('scoreRangeSortBy')
    expect(source).not.toContain('scoreRangeSortDirection')
    expect(source).not.toContain('toggleScoreRangeSortDirection')
    expect(source).toContain('FairnessAnalysisCharts')
    expect(source).toContain(':show-score-range="true"')
  })

  it('removes heatmap charts from fairness visuals', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('SideHeatmap')
    expect(source).not.toContain('SideMarginHeatmap')
  })

  it('removes volatility insight features from fairness analytics', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('buildVolatilityRows')
    expect(source).not.toContain('volatilityRows')
    expect(source).not.toContain('volatilityAlertCount')
    expect(source).not.toContain('変動指標 (Volatility)')
    expect(source).not.toContain('急変チーム件数')
    expect(source).not.toContain('openFairnessFromOperations')
  })

  it('removes operation speed/risk dashboard internals', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('submissionSpeedRows')
    expect(source).not.toContain('submissionSpeedSummary')
    expect(source).not.toContain('提出スピード詳細')
    expect(source).not.toContain('遅延上位提出者')
    expect(source).not.toContain('submissionDelayRows')
    expect(source).not.toContain('submissionTypeLabel')
    expect(source).not.toContain('speedStatusLabel')
  })

  it('lets slides switch entity labels independently and appears before award copy', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('slideAvailableLabels')
    expect(source).toContain('slideLabel')
    expect(source).toContain('setSlideLabel')
    expect(source).toContain(':label="slideLabel"')
    expect(source).toContain('announcementResultsSource')
    expect(source).toContain('announcementResults')
    expect(source).toContain('awardMetricLabel(slideLabel.value)')
    const slideHeadingIndex = source.indexOf("<h4>{{ $t('スライド') }}</h4>")
    const awardHeadingIndex = source.indexOf("<h4>{{ $t('表彰コピー') }}</h4>")
    expect(slideHeadingIndex).toBeGreaterThan(-1)
    expect(awardHeadingIndex).toBeGreaterThan(-1)
    expect(slideHeadingIndex).toBeLessThan(awardHeadingIndex)
  })

  it('shows slides by default and separates slide type from slide style', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain(':presentation-mode="true"')
    expect(source).not.toContain('showSlides')
    expect(source).not.toContain("$t('スライドを表示')")
    expect(source).not.toContain('slideSettingsOpen')
    expect(source).not.toContain('@close="showSlides = false"')
    expect(source).toContain('<option value="single">{{ $t(\'個別\') }}</option>')
    expect(source).toContain("$t('スライドスタイル')")
    expect(source).toContain('<option value="simple">{{ $t(\'簡易\') }}</option>')
    expect(source).toContain("$t('スライド言語')")
    expect(source).toContain(':language="slideLanguage"')
    expect(source).toContain(':slide-style="slideStyle"')
  })

  it('tracks report telemetry for section dwell, CTA clicks, and exports', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    const telemetry = load('src/utils/report-telemetry.ts')
    expect(source).toContain('trackAdminReportMetric')
    expect(source).toContain("metric: 'tab_enter'")
    expect(source).toContain("metric: 'tab_leave'")
    expect(source).toContain("emitReportMetric('cta_click'")
    expect(source).toContain("emitReportMetric('export_complete'")
    expect(telemetry).toContain('utab:admin-report-metric')
  })

  it('registers interpolation labels for report cards to avoid raw {placeholders}', () => {
    const messages = load('src/i18n/messages.ts')
    expect(messages).toContain("'現在表示: {result}'")
    expect(messages).toContain("'現在: {label} - {description}'")
    expect(messages).toContain("'表示するレポート': 'Report to display'")
    expect(messages).toContain("'提出状況を確認': 'Check submission status'")
    expect(messages).toContain("'要確認: {count}件'")
    expect(messages).toContain("'Gov勝率 {gov}%'")
    expect(messages).toContain("'順位変動あり: {count}件'")
  })

  it('provides an existing-report list with per-row display and delete actions', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('reportSnapshotRows')
    expect(source).toContain('existing-report-list')
    expect(source).toContain('existing-report-row')
    expect(source).toContain("$t('表示')")
    expect(source).toContain("$t('削除')")
    expect(source).toContain('onSelectedCompiledChange')
    expect(source).toContain('selectedCompiledId')
    expect(source).toContain('selectedCompiledId.value = currentCompiledId')
    expect(source).toContain('baselineCompiledOptions.value[0].compiledId')
    expect(source).toContain('openDeleteCompiledModal')
    expect(source).toContain('confirmDeleteCompiled')
    expect(source).toContain("$t('集計結果を削除')")
    expect(source).toContain("$t('この集計結果を削除しますか？')")
  })

  it('opens recomputation options in the detailed settings modal', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('showRecomputeOptions')
    expect(source).toContain('詳細設定')
    expect(source).toContain('recompute-modal')
    expect(source).toContain('v-model:team-ranking-priority-order')
    expect(source).toContain('v-model:adjudicator-ranking-priority-order')
    expect(source).toContain(':show-ranking-priority="true"')
    expect(source).not.toContain('v-model:ranking-preset')
    expect(source).not.toContain('v-model:ranking-order')
    expect(source).toContain(':show-source-rounds="false"')
    expect(source).not.toContain(':show-source-rounds="true"')
    expect(source).toContain('openRecomputeOptions')
    expect(source).toContain('cancelRecomputeOptions')
    expect(source).toContain('applyRecomputeOptions')
    expect(source).toContain('applyCompileDefaultsFromTournament')
    expect(source).toContain('normalizeRoundDefaults(tournament.user_defined_data?.round_defaults)')
  })

  it('keeps compile preparation independent from the operations tab', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('新規仮集計')
    expect(source).not.toContain('新規レポートを生成します。')
    expect(source).not.toContain('v-if="!compiled || showOperationsSection"')
  })

  it('removes submission-first migration guide note from the setup area', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).not.toContain('提出データ一本化ガイド')
    expect(source).not.toContain('migration-guide')
    expect(source).not.toContain('submissionsOperationsLink')
  })

  it('marks exception mode by displayed snapshot source in header and diff legend', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('displayedCompileSource')
    expect(source).toContain('isDisplayedRawSource')
    expect(source).toContain('compiled.value?.compile_source')
    expect(source).toContain('表示中の大会結果は例外モードで生成されました。')
    expect(source).toContain("v-if=\"isDisplayedRawSource\" class=\"raw-source-badge\"")
  })

  it('applies a selected snapshot as the displayed compiled data', () => {
    const source = load('src/views/admin/AdminTournamentCompiled.vue')
    expect(source).toContain('function applyCompiledSnapshot')
    expect(source).toContain('compiledStore.compiled = normalized')
    expect(source).toMatch(/watch\(\s*selectedCompiledId/)
  })
})
